import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Progress } from "./ui/progress";
import { Alert, AlertDescription } from "./ui/alert";
import { Separator } from "./ui/separator";
import {
  Activity,
  Thermometer,
  Wind,
  Droplets,
  Eye,
  Volume2,
  Waves,
  RefreshCw,
  Lightbulb,
  AlertTriangle,
  TrendingUp,
  Calendar,
  MapPin,
} from "lucide-react";
import { toast } from "sonner";

const EnvironmentalReport = ({ data, onRefresh, loading }) => {
  if (!data) return null;

  const {
    aqi_data,
    weather_data,
    noise_data,
    water_logging_risk,
    civic_complaints,
    ai_suggestions,
    location,
    ehs_score,
  } = data;
console.log("EHS Score:", ehs_score);
  const getAQIStatus = (aqi) => {
    if (aqi <= 50)
      return {
        status: "Good",
        color: "bg-green-500",
        bgColor: "bg-green-50",
        textColor: "text-green-700",
        borderColor: "border-green-200",
      };
    if (aqi <= 100)
      return {
        status: "Moderate",
        color: "bg-yellow-500",
        bgColor: "bg-yellow-50",
        textColor: "text-yellow-700",
        borderColor: "border-yellow-200",
      };
    if (aqi <= 150)
      return {
        status: "Unhealthy for Sensitive",
        color: "bg-orange-500",
        bgColor: "bg-orange-50",
        textColor: "text-orange-700",
        borderColor: "border-orange-200",
      };
    if (aqi <= 200)
      return {
        status: "Unhealthy",
        color: "bg-red-500",
        bgColor: "bg-red-50",
        textColor: "text-red-700",
        borderColor: "border-red-200",
      };
    if (aqi <= 300)
      return {
        status: "Very Unhealthy",
        color: "bg-purple-500",
        bgColor: "bg-purple-50",
        textColor: "text-purple-700",
        borderColor: "border-purple-200",
      };
    return {
      status: "Hazardous",
      color: "bg-red-800",
      bgColor: "bg-red-50",
      textColor: "text-red-900",
      borderColor: "border-red-300",
    };
  };

  const getWaterRiskColor = (risk) => {
    switch (risk) {
      case "low":
        return "text-green-600 bg-green-50 border-green-200";
      case "medium":
        return "text-yellow-600 bg-yellow-50 border-yellow-200";
      case "high":
        return "text-red-600 bg-red-50 border-red-200";
      default:
        return "text-gray-600 bg-gray-50 border-gray-200";
    }
  };
  // Helper to get badge color for noise level
  const getNoiseBadgeColor = (level) => {
    switch (level) {
      case "High":
        return "bg-red-500";
      case "Moderate":
        return "bg-yellow-500";
      case "Low":
        return "bg-green-500";
      default:
        return "bg-gray-500";
    }
  };
  const aqiStatus = getAQIStatus(aqi_data.aqi);

  const handleShare = () => {
    const shareText =
      `Environmental Report for ${location.address}:\n` +
      `AQI: ${aqi_data.aqi} (${aqiStatus.status})\n` +
      `Temperature: ${weather_data.temperature}°C\n` +
      `Humidity: ${weather_data.humidity}%\n` +
      `Wind: ${weather_data.wind_speed} km/h\n` +
      `Generated by EcoSphere`;

    if (navigator.share) {
      navigator.share({
        title: "Environmental Report",
        text: shareText,
      });
    } else {
      navigator.clipboard.writeText(shareText);
      toast.success("Report copied to clipboard!");
    }
  };
  console.log("EnvironmentalReport data:", data);
  return (
    <div className="space-y-6" data-testid="environmental-report">
      {/* Header */}

      <Card className="shadow-md border border-emerald-100 p-4 rounded-lg">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-center mb-4">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            🌿 Environmental Report Card
          </h2>
          <Button
            variant="outline"
            onClick={onRefresh}
            disabled={loading}
            className="flex items-center gap-2 mt-2 sm:mt-0"
          >
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
        </div>

        {/* Summary Metrics */}
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
  {/* EHS Score */}
  <div className="bg-green-50 rounded-lg p-4 text-center">
    <Badge variant="outline" className="mb-1">
      EHS
    </Badge>
    <p className="text-2xl font-bold text-green-600">
      {/* Use the score from the ehs_score object */}
      {data.ehs_score?.score || "N/A"}
    </p>
    <p className="text-sm text-gray-600">Environmental Health</p>
  </div>

  {/* AQI */}
  <div className="bg-yellow-50 rounded-lg p-4 text-center">
    <Badge variant="outline" className="mb-1">
      AQI
    </Badge>
    <p className="text-2xl font-bold text-yellow-700">
      {data.aqi_data?.aqi || "N/A"}
    </p>
    <p className="text-sm text-gray-600">Air Quality Index</p>
  </div>

  {/* Pollution Index (PM2.5) */}
  <div className="bg-orange-50 rounded-lg p-4 text-center">
    <Wind className="h-6 w-6 text-orange-600 mx-auto mb-1" />
    <p className="text-2xl font-bold text-orange-700">
        {data.aqi_data?.pm25 || "N/A"}
    </p>
    <p className="text-sm text-gray-600">PM2.5 (μg/m³)</p>
  </div>

  {/* Noise Level */}
  {data.ehs_score?.breakdown?.estimatedDb && (
    <div className="bg-blue-50 rounded-lg p-4 text-center">
      <Volume2 className="h-6 w-6 text-blue-600 mx-auto mb-1" />
      <p className="text-2xl font-bold text-blue-700">
        {/* Use the estimatedDb from the EHS breakdown */}
        {data.ehs_score.breakdown.estimatedDb} dB
      </p>
      <p className="text-sm text-gray-600">Est. Noise Level</p>
    </div>
  )}
</div>

        {/* AI Insights */}
        {data.ai_suggestions && data.ai_suggestions.length > 0 && (
          <div>
            <h4 className="font-semibold text-gray-700 mb-2">AI Insights</h4>
            <ul className="space-y-2">
              {data.ai_suggestions.map((tip, index) => (
                <li
                  key={index}
                  className="flex items-start gap-2 text-gray-700 bg-emerald-50 px-3 py-2 rounded-lg border border-emerald-100"
                >
                  <span className="text-emerald-600 mt-0.5">✔️</span>
                  {tip}
                </li>
              ))}
            </ul>
          </div>
        )}
      </Card>


      {/* AQI Section */}
      <Card
        className={`report-card border-l-4 ${aqiStatus.borderColor} ${aqiStatus.bgColor}`}
      >
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-xl">
            <Activity className={`h-6 w-6 ${aqiStatus.textColor}`} />
            Air Quality Index (AQI)
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <div className="text-4xl font-bold text-gray-800">
                {aqi_data.aqi}
              </div>
              <Badge className={`${aqiStatus.color} text-white mt-2`}>
                {aqiStatus.status}
              </Badge>
            </div>
            <div className="text-right">
              <Progress
                value={(aqi_data.aqi / 500) * 100}
                className="w-32 h-3"
              />
              <p className="text-sm text-gray-600 mt-1">Max: 500</p>
            </div>
          </div>

          <Separator />

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div className="text-center">
              <p className="text-sm text-gray-600">PM2.5</p>
              <p className="text-lg font-semibold">{aqi_data.pm25} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">PM10</p>
              <p className="text-lg font-semibold">{aqi_data.pm10} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">O₃</p>
              <p className="text-lg font-semibold">{aqi_data.o3} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">NO₂</p>
              <p className="text-lg font-semibold">{aqi_data.no2} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">SO₂</p>
              <p className="text-lg font-semibold">{aqi_data.so2} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">CO</p>
              <p className="text-lg font-semibold">{aqi_data.co} mg/m³</p>
            </div>
          </div>

          {/* 3-day forecast */}
          {aqi_data.forecast && aqi_data.forecast.length > 0 && (
            <div className="mt-4">
              <h4 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                3-Day AQI Forecast
              </h4>
              <div className="grid grid-cols-3 gap-2">
                {aqi_data.forecast.map((day, index) => (
                  <div
                    key={index}
                    className="text-center p-3 bg-white rounded-lg border"
                  >
                    <p className="text-xs text-gray-600">{day.day}</p>
                    <p className="text-lg font-bold">{day.aqi}</p>
                    <p className="text-xs text-gray-500">{day.status}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Weather Section */}
      <Card className="report-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-xl">
            <Thermometer className="h-6 w-6 text-orange-500" />
            Weather Conditions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center p-4 bg-gradient-to-br from-orange-50 to-red-50 rounded-lg">
              <Thermometer className="h-8 w-8 text-orange-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-800">
                {weather_data.temperature}°C
              </p>
              <p className="text-sm text-gray-600">Temperature</p>
            </div>

            <div className="text-center p-4 bg-gradient-to-br from-cyan-50 to-blue-50 rounded-lg">
              <Droplets className="h-8 w-8 text-cyan-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-800">
                {weather_data.humidity}%
              </p>
              <p className="text-sm text-gray-600">Humidity</p>
            </div>

            <div className="text-center p-4 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg">
              <Wind className="h-8 w-8 text-blue-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-800">
                {weather_data.wind_speed}
              </p>
              <p className="text-sm text-gray-600">Wind km/h</p>
            </div>

            <div className="text-center p-4 bg-gradient-to-br from-gray-50 to-slate-50 rounded-lg">
              <Eye className="h-8 w-8 text-gray-500 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-800">
                {weather_data.visibility}
              </p>
              <p className="text-sm text-gray-600">Visibility km</p>
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <span className="text-sm text-gray-600">Wind Direction</span>
              <span className="font-semibold">
                {weather_data.wind_direction}°
              </span>
            </div>
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <span className="text-sm text-gray-600">Pressure</span>
              <span className="font-semibold">{weather_data.pressure} hPa</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Additional Environmental Factors */}
      <div className="grid md:grid-cols-2 gap-6">
        <Card className="report-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Volume2 className="h-5 w-5 text-purple-500" />
              Noise Pollution
            </CardTitle>
          </CardHeader>
          <CardContent>
            {noise_data ? (
              <div className="text-center">
                <div className="text-3xl font-bold text-gray-800">
                  {noise_data.db_range}
                </div>
                <Badge
                  className={`${getNoiseBadgeColor(
                    noise_data.level
                  )} text-white mt-1`}
                >
                  {noise_data.level}
                </Badge>
                <p className="text-sm text-gray-600 mt-2">{noise_data.desc}</p>
              </div>
            ) : (
              <p className="text-sm text-gray-500 text-center">
                Noise data not available.
              </p>
            )}
          </CardContent>
        </Card>

        <Card className="report-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Waves className="h-5 w-5 text-blue-500" />
              Water Logging Risk
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-center">
              <Badge
                className={`text-lg px-4 py-2 ${getWaterRiskColor(
                  water_logging_risk
                )}`}
              >
                {water_logging_risk.toUpperCase()} RISK
              </Badge>
              <p className="text-sm text-gray-600 mt-3">
                Based on topography, drainage, and historical data
              </p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* AI Suggestions */}
      {ai_suggestions && ai_suggestions.length > 0 && (
        <Card className="report-card border-l-4 border-emerald-500 bg-gradient-to-r from-emerald-50 to-teal-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-emerald-700">
              <Lightbulb className="h-6 w-6" />
              AI-Powered Recommendations
            </CardTitle>
            <p className="text-sm text-emerald-600">
              Personalized suggestions based on current environmental conditions
            </p>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {ai_suggestions.map((suggestion, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 p-3 bg-white rounded-lg shadow-sm"
                >
                  <div className="w-6 h-6 bg-emerald-500 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-white text-sm font-bold">
                      {index + 1}
                    </span>
                  </div>
                  <p className="text-gray-700">{suggestion}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Civic Complaints */}
      {civic_complaints && civic_complaints.length > 0 && (
        <Card className="report-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-orange-500" />
              Recent Civic Issues Nearby
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {civic_complaints.slice(0, 3).map((complaint, index) => (
                <Alert key={index} className="border-orange-200">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium capitalize">
                          {complaint.report_type.replace("_", " ")}
                        </p>
                        <p className="text-sm text-gray-600 mt-1">
                          {complaint.description}
                        </p>
                      </div>
                      <Badge
                        variant={
                          complaint.severity === "high"
                            ? "destructive"
                            : complaint.severity === "medium"
                              ? "default"
                              : "secondary"
                        }
                      >
                        {complaint.severity}
                      </Badge>
                    </div>
                  </AlertDescription>
                </Alert>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <Button
          onClick={handleShare}
          className="flex-1 bg-emerald-500 hover:bg-emerald-600"
          data-testid="share-report-btn"
        >
          Share Report
        </Button>
        <Button
          variant="outline"
          className="flex-1"
          onClick={() => window.print()}
          data-testid="print-report-btn"
        >
          Print Report
        </Button>
      </div>
    </div>
  );
};

export default EnvironmentalReport;
