import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Progress } from "./ui/progress";
import { Alert, AlertDescription } from "./ui/alert";
import { Separator } from "./ui/separator";
import {
  Activity,
  Thermometer,
  Wind,
  Droplets,
  Eye,
  Volume2,
  Waves,
  RefreshCw,
  Lightbulb,
  AlertTriangle,
  TrendingUp,
  Calendar,
  MapPin,
} from "lucide-react";
import { toast } from "sonner";

const CircularEHS = ({ value }) => {
  const radius = 50;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (value / 100) * circumference;

  // Dynamic color based on score
  const getColor = (v) => {
    if (v >= 80) return "stroke-green-500 text-green-500";
    if (v >= 60) return "stroke-yellow-500 text-yellow-500";
    if (v >= 40) return "stroke-orange-500 text-orange-500";
    return "stroke-red-500 text-red-500";
  };

  return (
    <div className="relative w-[120px] h-[120px] flex items-center justify-center">
      <svg
        className="transform -rotate-90"
        width="120"
        height="120"
        viewBox="0 0 120 120"
      >
        {/* Background circle */}
        <circle
          cx="60"
          cy="60"
          r={radius}
          stroke="#e5e7eb"
          strokeWidth="10"
          fill="none"
        />
        {/* Foreground progress circle */}
        <circle
          cx="60"
          cy="60"
          r={radius}
          className={getColor(value)}
          strokeWidth="10"
          fill="none"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
          style={{ transition: "stroke-dashoffset 1s ease" }}
        />
      </svg>

      {/* Text inside circle */}
      <div className="absolute text-center">
        <p className="text-2xl font-bold text-gray-800">{value}%</p>
        <p className="text-sm text-gray-500">EHS Score</p>
      </div>
    </div>
  );
};

const EnvironmentalReport = ({ data, onRefresh, loading }) => {
  if (!data) return null;

  const {
    aqi_data,
    weather_data,
    noise_data,
    water_logging_risk,
    civic_complaints,
    ai_suggestions,
    location,
    ehs_score,
  } = data;
  console.log("EHS Score:", ehs_score);
  const getAQIStatus = (aqi) => {
    if (aqi <= 50)
      return {
        status: "Good",
        color: "bg-green-500",
        bgColor: "bg-green-50",
        textColor: "text-green-700",
        borderColor: "border-green-200",
      };
    if (aqi <= 100)
      return {
        status: "Moderate",
        color: "bg-yellow-500",
        bgColor: "bg-yellow-50",
        textColor: "text-yellow-700",
        borderColor: "border-yellow-200",
      };
    if (aqi <= 150)
      return {
        status: "Unhealthy for Sensitive",
        color: "bg-orange-500",
        bgColor: "bg-orange-50",
        textColor: "text-orange-700",
        borderColor: "border-orange-200",
      };
    if (aqi <= 200)
      return {
        status: "Unhealthy",
        color: "bg-red-500",
        bgColor: "bg-red-50",
        textColor: "text-red-700",
        borderColor: "border-red-200",
      };
    if (aqi <= 300)
      return {
        status: "Very Unhealthy",
        color: "bg-purple-500",
        bgColor: "bg-purple-50",
        textColor: "text-purple-700",
        borderColor: "border-purple-200",
      };
    return {
      status: "Hazardous",
      color: "bg-red-800",
      bgColor: "bg-red-50",
      textColor: "text-red-900",
      borderColor: "border-red-300",
    };
  };

  const getWaterRiskColor = (risk) => {
    switch (risk) {
      case "low":
        return "text-green-600 bg-green-50 border-green-200";
      case "medium":
        return "text-yellow-600 bg-yellow-50 border-yellow-200";
      case "high":
        return "text-red-600 bg-red-50 border-red-200";
      default:
        return "text-gray-600 bg-gray-50 border-gray-200";
    }
  };
  // Helper to get badge color for noise level
  const getNoiseBadgeColor = (level) => {
    switch (level) {
      case "High":
        return "bg-red-500";
      case "Moderate":
        return "bg-yellow-500";
      case "Low":
        return "bg-green-500";
      default:
        return "bg-gray-500";
    }
  };
  const aqiStatus = getAQIStatus(aqi_data.aqi);

  const handleShare = () => {
    const shareText =
      `Environmental Report for ${location.address}:\n` +
      `AQI: ${aqi_data.aqi} (${aqiStatus.status})\n` +
      `Temperature: ${weather_data.temperature}°C\n` +
      `Humidity: ${weather_data.humidity}%\n` +
      `Wind: ${weather_data.wind_speed} km/h\n` +
      `Generated by EcoSphere`;

    if (navigator.share) {
      navigator.share({
        title: "Environmental Report",
        text: shareText,
      });
    } else {
      navigator.clipboard.writeText(shareText);
      toast.success("Report copied to clipboard!");
    }
  };
  console.log("EnvironmentalReport data:", data);
  return (
    <div className="space-y-6" data-testid="environmental-report">
      {/* Header */}

      <Card className="shadow-md border border-emerald-100 p-4 rounded-lg">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-center mb-4">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            🌿 Environmental Report Card
          </h2>
          <Button
            variant="outline"
            onClick={onRefresh}
            disabled={loading}
            className="flex items-center gap-2 mt-2 sm:mt-0"
          >
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>

        </div>

        <p className="text-gray-600 mt-1 flex items-center gap-1">
          <MapPin className="h-4 w-4" />
          {location.address}
        </p>

        {/* Summary Metrics */}
        <div className="space-y-6 mb-4">
          {/* Row 1: Centered EHS */}
          <div className="flex justify-center">
            <Card className="bg-green-100 text-center card-hover relative w-[160px]">
              <CardContent className="p-4 flex flex-col items-center justify-center">
                <CircularEHS value={Math.round(data.ehs_score?.score || 0)} />
              </CardContent>
            </Card>
          </div>

          {/* Row 2: AQI, Weather, Noise */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {/* AQI */}
            <div className="bg-yellow-100 rounded-lg p-4 text-center flex flex-col items-center justify-center">
              <Badge variant="outline" className="mb-1">
                AQI
              </Badge>
              <p className="text-2xl font-bold text-yellow-700">
                {data.ehs_score?.breakdown?.airScore || "N/A"}
              </p>
              <p className="text-sm text-gray-600">AQI score</p>
            </div>

            {/* Weather */}
            <div className="bg-orange-100 rounded-lg p-4 text-center flex flex-col items-center justify-center">
              <Wind className="h-6 w-6 text-orange-600 mx-auto mb-1" />
              <p className="text-2xl font-bold text-orange-700">
                {data.ehs_score?.breakdown?.weatherScore || "N/A"}
              </p>
              <p className="text-sm text-gray-600">Weather score</p>
            </div>

            {/* Noise */}
            {data.ehs_score?.breakdown?.noiseScore && (
              <div className="bg-blue-100 rounded-lg p-4 text-center flex flex-col items-center justify-center">
                <Volume2 className="h-6 w-6 text-blue-600 mx-auto mb-1" />
                <p className="text-2xl font-bold text-blue-700">
                  {data.ehs_score.breakdown.noiseScore}
                </p>
                <p className="text-sm text-gray-600">Est. Noise Level</p>
              </div>
            )}
          </div>
        </div>


        {/* AI Insights */}
        {data.ai_suggestions && data.ai_suggestions.length > 0 && (
          <div>
            <h4 className="font-semibold text-gray-700 mb-2">AI Insights</h4>
            <ul className="space-y-2">
              {data.ai_suggestions.map((tip, index) => (
                <li
                  key={index}
                  className="flex items-start gap-2 text-gray-700 bg-emerald-50 px-3 py-2 rounded-lg border border-emerald-100"
                >
                  <span className="text-emerald-600 mt-0.5">✔️</span>
                  {tip}
                </li>
              ))}
            </ul>
          </div>
        )}
      </Card>


      {/* AQI Section */}
      <Card
        className={`report-card border-l-4 ${aqiStatus.borderColor} ${aqiStatus.bgColor}`}
      >
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-xl">
            <Activity className={`h-6 w-6 ${aqiStatus.textColor}`} />
            Air Quality Index (AQI)
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <div className="text-4xl font-bold text-gray-800">
                {aqi_data.aqi}
              </div>
              <Badge className={`${aqiStatus.color} text-white mt-2`}>
                {aqiStatus.status}
              </Badge>
            </div>
            <div className="text-right">
              <Progress
                value={(aqi_data.aqi / 500) * 100}
                className="w-32 h-3"
              />
              <p className="text-sm text-gray-600 mt-1">Max: 500</p>
            </div>
          </div>

          <Separator />

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div className="text-center">
              <p className="text-sm text-gray-600">PM2.5</p>
              <p className="text-lg font-semibold">{aqi_data.pm25} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">PM10</p>
              <p className="text-lg font-semibold">{aqi_data.pm10} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">O₃</p>
              <p className="text-lg font-semibold">{aqi_data.o3} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">NO₂</p>
              <p className="text-lg font-semibold">{aqi_data.no2} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">SO₂</p>
              <p className="text-lg font-semibold">{aqi_data.so2} μg/m³</p>
            </div>
            <div className="text-center">
              <p className="text-sm text-gray-600">CO</p>
              <p className="text-lg font-semibold">{aqi_data.co} mg/m³</p>
            </div>
          </div>

          {/* 3-day forecast */}
          {aqi_data.forecast && aqi_data.forecast.length > 0 && (
            <div className="mt-4">
              <h4 className="font-semibold text-gray-700 mb-3 flex items-center gap-2">
                <TrendingUp className="h-4 w-4" />
                3-Day AQI Forecast
              </h4>
              <div className="grid grid-cols-3 gap-2">
                {aqi_data.forecast.map((day, index) => (
                  <div
                    key={index}
                    className="text-center p-3 bg-white rounded-lg border"
                  >
                    <p className="text-xs text-gray-600">{day.day}</p>
                    <p className="text-lg font-bold">{day.aqi}</p>
                    <p className="text-xs text-gray-500">{day.status}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      
      {/* AI Suggestions */}
      {ai_suggestions && ai_suggestions.length > 0 && (
        <Card className="report-card border-l-4 border-emerald-500 bg-gradient-to-r from-emerald-50 to-teal-50">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-emerald-700">
              <Lightbulb className="h-6 w-6" />
              AI-Powered Recommendations
            </CardTitle>
            <p className="text-sm text-emerald-600">
              Personalized suggestions based on current environmental conditions
            </p>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {ai_suggestions.map((suggestion, index) => (
                <li
                  key={index}
                  className="flex items-start gap-3 p-3 bg-white rounded-lg shadow-sm"
                >
                  <div className="w-6 h-6 bg-emerald-500 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                    <span className="text-white text-sm font-bold">
                      {index + 1}
                    </span>
                  </div>
                  <p className="text-gray-700">{suggestion}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Civic Complaints */}
      {civic_complaints && civic_complaints.length > 0 && (
        <Card className="report-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-orange-500" />
              Recent Civic Issues Nearby
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {civic_complaints.slice(0, 3).map((complaint, index) => (
                <Alert key={index} className="border-orange-200">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium capitalize">
                          {complaint.report_type.replace("_", " ")}
                        </p>
                        <p className="text-sm text-gray-600 mt-1">
                          {complaint.description}
                        </p>
                      </div>
                      <Badge
                        variant={
                          complaint.severity === "high"
                            ? "destructive"
                            : complaint.severity === "medium"
                              ? "default"
                              : "secondary"
                        }
                      >
                        {complaint.severity}
                      </Badge>
                    </div>
                  </AlertDescription>
                </Alert>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <Button
          onClick={handleShare}
          className="flex-1 bg-emerald-500 hover:bg-emerald-600"
          data-testid="share-report-btn"
        >
          Share Report
        </Button>
        <Button
          variant="outline"
          className="flex-1"
          onClick={() => window.print()}
          data-testid="print-report-btn"
        >
          Print Report
        </Button>
      </div>
    </div>
  );
};

export default EnvironmentalReport;
